name: R pkgdown Multi Version docs
author: Insights Engineering
description: Generates multisite R documentation created with pkgdown.
branding:
  icon: 'anchor'
  color: 'orange'
inputs:
  path:
    description: Path to package's root
    required: false
    default: "."
  default-landing-page:
    description: |
      The default branch or tag on gh-pages that corresponds to the landing page.
      For instance, if your root index page on gh-pages is built using the 'main'
      branch, then the root page of the website will correspond to this page.
      If 'latest-tag' is selected, then the latest version will become the default.
    default: main
    required: false
  branches-or-tags-to-list:
    description:
      Which branches or tags should be listed under the
      'Versions' dropdown menu on the landing page?
      This input should be a regular expression in R.
    required: false
    default: >-
      ^main$|^devel$|^pre-release$|^latest-tag$|^develop$|^v([0-9]+\\.)?([0-9]+\\.)?([0-9]+)$
  insert-after-section:
    description:
      After which section in the navbar should the 'Versions'
      dropdown be added? Choose between 'Reference' and 'Changelog'
      for the surest of choices.
    required: false
    default: Changelog
  version-tab:
    description: |
      Configuration how should the dropdownlist appear for multiple versions.
      It should be set as an ASCII text representation of an R list object
      Example:
      """
      list(config = list(
              tooltip = list(
                main = "Tooltip for main branch"
              ),
              text = list(
                main = "main branch"
              )
            ))
      """
      String should be quoted with " sign
    required: false
    default: ""
  refs-order:
    description: |
      The order refs (other than semantic versions) should
      appear in the drop-down list.
      Example:
      c("main", "devel", "pre-release", "latest-tag")
    required: false
    default: ""



runs:
  using: 'composite'
  steps:
    - name: Create copy of latest tag
      run: |
        cd ${{ inputs.path }}
        set +o pipefail
        latest_tag=$(ls -1d * \
          | grep -E "^v([0-9]+\.)?([0-9]+\.)?([0-9]+)$" \
          | sort -t "." -k1,1n -k2,2n -k3,3n \
          | tail -1)
        set -o pipefail
        rm -rf latest-tag
        [[ "${latest_tag}" != "" ]] \
          && cp -r "${latest_tag}" latest-tag \
          || echo "No tags found, not creating symlink for latest tag"
      shell: bash

    - name: Create redirect page
      run: |
        cd ${{ inputs.path }}
        cp "${GITHUB_ACTION_PATH}/redirect.html" index.html
        perl -p -i -e \
          "s@DEFAULT_LANDING_PAGE@${{ inputs.default-landing-page }}@g" \
          index.html
        perl -p -i -e \
          "s@REPOSITORY@${{ github.event.repository.name }}@g" \
          index.html
        perl -p -i -e \
          "s@OWNER@${{ github.repository_owner }}@g" \
          index.html
        touch .nojekyll
      shell: bash

    - name: Run multi-version site creation script
      run: |
        source(file.path(
          Sys.getenv("GITHUB_ACTION_PATH"), "core.R")
        )
        setwd("${{ inputs.path }}")
        update_content(
          refs_to_list = "${{ inputs.branches-or-tags-to-list }}",
          refs_order = ${{ inputs.refs-order }},
          insert_after_section = "${{ inputs.insert-after-section }}",
          version_tab = '${{ inputs.version-tab }}'
        )
      shell: Rscript {0}

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[actions skip] Built site for ${{ github.event.repository.name }}@${{ github.sha }}"
        repository: ${{ inputs.path }}
        commit_user_name: github-actions
        commit_user_email: 41898282+github-actions[bot]
        branch: gh-pages
        create_branch: true
